name: traffic-sign-recognition
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - jupyter
  - pip:
      - opencv-python
      - torch
      - torchvision
      - tqdm